name: Deploy Astro Site to GitHub Pages

on:
  push:
    branches:
      - main  # Asegúrate de que 'main' es tu rama de desarrollo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.14.1'  # Actualiza a la versión de Node.js que sea compatible

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Asegúrate de que 'dist' es tu carpeta de salida
